- name: Setup Opensearch
  hosts: all
  become: true

  tasks:
    - name: Copy docker install script to remote hosts
      copy:
        src: configure_docker.sh
        dest: "/home/{{ ansible_user }}/configure_docker.sh"
        mode: "u+x"
      tags: docker

    - name: Execute docker install script
      become_user: root
      command: "sh /home/{{ ansible_user }}/configure_docker.sh -u {{ ansible_user }}"
      tags: docker
      async: 3600
      poll: 5
      register: cmd_output

    - name: Display command output
      debug:
        var: cmd_output.stdout_lines

    - name: Turn off swap
      command: swapoff -a
      tags: sysctl
      become_user: root

    - name: Increase the number of memory maps available to OpenSearch
      lineinfile:
        path: /etc/sysctl.conf
        line: "vm.max_map_count=262144"
        insertafter: EOF
        state: present
      become: true
      tags: sysctl

    - name: Reload sysctl
      command: sysctl -p
      tags: sysctl
      become: true

    - name: Update no_proxy setting
      lineinfile:
        path: /etc/profile.d/proxy_setup.sh
        line: "export no_proxy=127.0.0.1,localhost,{% for host in groups['all'] %}{{ hostvars[host]['ansible_host'] }}{% if not loop.last %},{% endif %}{% endfor %}"
        search_string: "export no_proxy"
        state: present
      tags: proxy
      become_user: root

    - name: Update NO_PROXY setting
      lineinfile:
        path: /etc/profile.d/proxy_setup.sh
        line: "export NO_PROXY=127.0.0.1,localhost,{% for host in groups['all'] %}{{ hostvars[host]['ansible_host'] }}{% if not loop.last %},{% endif %}{% endfor %}"
        search_string: "export NO_PROXY"
        state: present
      tags: proxy
      become_user: root

    - name: Create data directory for opensearch
      file:
        path: "/home/{{ ansible_user }}/data"
        state: directory
        mode: "0777"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      become: true
      become_user: root

    - name: Generate opensearch compose file
      script: |
        ./gen_os_compose.sh \
        --cluster "{{ cluster_name | default('os-cluster') }}"  \
        --node os-"{{ inventory_hostname }}"  \
        --roles "{{ 'cluster_manager' if 'manager' in inventory_hostname else 'data,ingest' }}"  \
        --managers "{% for host in groups['cluster_manager'] %}{{ hostvars[host]['ansible_host'] }}{% if not loop.last %},{% endif %}{% endfor %}"  \
        --data "{% for host in groups['cluster_data'] %}{{ hostvars[host]['ansible_host'] }}{% if not loop.last %},{% endif %}{% endfor %}" \
        --user "{{ ansible_user }}"

    - name: Change permission of opensearch compose file
      file:
        path: /home/{{ ansible_user }}/docker-compose.yml
        mode: "0755"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      become_user: root
      become: true

    - name: Install opensearch with docker compose
      tags: docker
      become_user: root
      command: docker compose up -d
